name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@latest
      - name: esy '@fetch-core' 
        run: esy '@fetch-core'
      - name: esy '@fetch-core' test 
        run: esy '@fetch-core' test
      - if: matrix.os != 'windows-latest'
        run: esy '@fetch-core' format 
      - name: esy '@fetch-native-lwt' 
        run: esy '@fetch-native-lwt'
      - if: matrix.os != 'windows-latest'
        run: esy '@fetch-native-lwt' format
      - name: esy '@example-lwt' 
        run: esy '@example-lwt'
      - name: esy '@example-lwt' get
        run: esy '@example-lwt' get
