name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@latest
      - name: Build Fetch_Core 
        run: esy '@fetch-core'
      - name: Run tests for Fetch_Core 
        run: esy '@fetch-core' test
      - name: Build Fetch_Lwt 
        run: esy '@fetch-native-lwt'
      - name: Build Fetch_Lwt-example 
        run: esy '@example-lwt'
      - name: Run Fetch_Lwt-example
        run: esy '@example-lwt' get
      - if: matrix.os != 'windows-latest'
        run: esy dune build @fmt --root .
