name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-2016, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@latest
      - name: Build packages
        run: |
          esy '@fetch-core'
          esy '@fetch-native-lwt'
      - name: Run esy 
        run: esy 
      - name: Check code formatting
        run: esy dune build @fmt --root .
      - name: Run tests
        run: esy test
      - name: Run example
        run: esy example
