name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - if: matrix.os == 'windows-latest'
        run: choco install openssl
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g @esy-nightly/esy
      - name: Build packages
        run: |
          esy @fetch-core
          esy @fetch-native-lwt
          esy
      - name: Check code formatting
        run: esy dune build @fmt --root .
      - name: Run tests
        run: esy test
      - name: Run example
        run: esy example
